### ISSUE TITLE
cinder-volume can't running on ceph-osd node

### ISSUE THREAD

**Issue by liuhongjiang** [liuhongjiang/vagrant-kolla-ceph-deploy#3]
if the control node and the ceph-osd node is different, it will report:
```
Running command: 'cinder-volume --config-file /etc/cinder/cinder.conf'
Traceback (most recent call last):
  File "/usr/bin/cinder-volume", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/cinder/cmd/volume.py", line 76, in main
    logging.setup(CONF, "cinder")
  File "/usr/lib/python2.7/site-packages/oslo_log/log.py", line 269, in setup
    _setup_logging_from_conf(conf, product_name, version)
  File "/usr/lib/python2.7/site-packages/oslo_log/log.py", line 366, in _setup_logging_from_conf
    filelog = file_handler(logpath)
  File "/usr/lib64/python2.7/logging/handlers.py", line 392, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib64/python2.7/logging/__init__.py", line 902, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib64/python2.7/logging/__init__.py", line 925, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/var/log/kolla/cinder/cinder-volume.log'
```

**Comment by liuhongjiang** [comment]
please refer to this commit: https://review.openstack.org/#/c/393201/
